### ISSUE TITLE
Custom words don't appear to work

### ISSUE THREAD

**Issue by AZMCode** [conradludgate/wordle#17]
Currently running `cl-wordle = "0.2.2"` from crates.io, and made a small script to pick a random word from `cl_wordle::words::ACCEPTED`, and run it using the `wordle custom <word>` command.

Found that the words weren't quite working.

Made a loop to see if this was a one-off, but 3081 words later none of them worked.

Edit: I just read the code and it appears that `cl_wordle::words::FINAL` is the wordlist accepted, excuse the mistake. Closing.

**Comment by conradludgate** [comment]
I could probably loosen up that restriction, but I felt it appropriate for now to make it like that
