### ISSUE TITLE
Installing cl-wordle gives me a "error: linker 'link.exe' not found (Windows 11)

### ISSUE THREAD

**Issue by tylerjgarland** [conradludgate/wordle#2]
I'll install a VS, but seems like a strange requirement. 

```
error: linker `link.exe` not found
  |
  = note: program not found

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013, VS 2015, VS 2017 or VS 2019 was installed with the Visual C++ option

error: could not compile `memchr` due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cl-wordle v0.1.1`, intermediate artifacts can be found at `C:\Users\XXX\AppData\Local\Temp\cargo-install03yD85`
```

**Comment by tylerjgarland** [comment]
Needed to install this. [Build Tools](https://stackoverflow.com/a/55603112)

**Comment by tylerjgarland** [comment]
The errors continue.

```
error[E0433]: failed to resolve: maybe a missing crate `sys`?
  --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\lib.rs:24:9
   |
24 | pub use sys::size::terminal_size;
   |         ^^^ maybe a missing crate `sys`?

error[E0433]: failed to resolve: maybe a missing crate `sys`?
  --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\lib.rs:27:9
   |
27 | pub use sys::tty::{is_tty, get_tty};
   |         ^^^ maybe a missing crate `sys`?

error[E0433]: failed to resolve: maybe a missing crate `sys`?
 --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\async.rs:5:5
  |
5 | use sys::tty::get_tty;
  |     ^^^ maybe a missing crate `sys`?

error[E0433]: failed to resolve: maybe a missing crate `sys`?
  --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:28:5
   |
28 | use sys::attr::{get_terminal_attr, raw_terminal_attr, set_terminal_attr};
   |     ^^^ maybe a missing crate `sys`?

error[E0432]: unresolved import `sys`
  --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:29:5
   |
29 | use sys::Termios;
   |     ^^^ maybe a missing crate `sys`?

error[E0425]: cannot find function `get_tty` in this scope
  --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\async.rs:14:36
   |
14 |     thread::spawn(move || for i in get_tty().unwrap().bytes() {
   |                                    ^^^^^^^ not found in this scope

error[E0425]: cannot find function `get_tty` in this scope
  --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\async.rs:43:36
   |
43 |     thread::spawn(move || for i in get_tty().unwrap().bytes() {
   |                                    ^^^^^^^ not found in this scope

error[E0425]: cannot find function `set_terminal_attr` in this scope
  --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:45:9
   |
45 |         set_terminal_attr(&self.prev_ios).unwrap();
   |         ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `get_terminal_attr` in this scope
   --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:102:23
    |
102 |         let mut ios = get_terminal_attr()?;
    |                       ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `raw_terminal_attr` in this scope
   --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:105:9
    |
105 |         raw_terminal_attr(&mut ios);
    |         ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `set_terminal_attr` in this scope
   --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:107:9
    |
107 |         set_terminal_attr(&ios)?;
    |         ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `set_terminal_attr` in this scope
   --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:119:9
    |
119 |         set_terminal_attr(&self.prev_ios)?;
    |         ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `get_terminal_attr` in this scope
   --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:125:23
    |
125 |         let mut ios = get_terminal_attr()?;
    |                       ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `raw_terminal_attr` in this scope
   --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:126:9
    |
126 |         raw_terminal_attr(&mut ios);
    |         ^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `set_terminal_attr` in this scope
   --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:127:9
    |
127 |         set_terminal_attr(&ios)?;
    |         ^^^^^^^^^^^^^^^^^ not found in this scope

   Compiling addr2line v0.17.0
   Compiling object v0.27.1
Some errors have detailed explanations: E0425, E0432, E0433.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `termion` due to 15 previous errors
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cl-wordle v0.1.1`, intermediate artifacts can be found at `C:\Users\X\AppData\Local\Temp\cargo-install2SzPG7`
```

**Comment by jixperson** [comment]
> The errors continue.
> 
> ```
> error[E0433]: failed to resolve: maybe a missing crate `sys`?
>   --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\lib.rs:24:9
>    |
> 24 | pub use sys::size::terminal_size;
>    |         ^^^ maybe a missing crate `sys`?
> 
> error[E0433]: failed to resolve: maybe a missing crate `sys`?
>   --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\lib.rs:27:9
>    |
> 27 | pub use sys::tty::{is_tty, get_tty};
>    |         ^^^ maybe a missing crate `sys`?
> 
> error[E0433]: failed to resolve: maybe a missing crate `sys`?
>  --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\async.rs:5:5
>   |
> 5 | use sys::tty::get_tty;
>   |     ^^^ maybe a missing crate `sys`?
> 
> error[E0433]: failed to resolve: maybe a missing crate `sys`?
>   --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:28:5
>    |
> 28 | use sys::attr::{get_terminal_attr, raw_terminal_attr, set_terminal_attr};
>    |     ^^^ maybe a missing crate `sys`?
> 
> error[E0432]: unresolved import `sys`
>   --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:29:5
>    |
> 29 | use sys::Termios;
>    |     ^^^ maybe a missing crate `sys`?
> 
> error[E0425]: cannot find function `get_tty` in this scope
>   --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\async.rs:14:36
>    |
> 14 |     thread::spawn(move || for i in get_tty().unwrap().bytes() {
>    |                                    ^^^^^^^ not found in this scope
> 
> error[E0425]: cannot find function `get_tty` in this scope
>   --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\async.rs:43:36
>    |
> 43 |     thread::spawn(move || for i in get_tty().unwrap().bytes() {
>    |                                    ^^^^^^^ not found in this scope
> 
> error[E0425]: cannot find function `set_terminal_attr` in this scope
>   --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:45:9
>    |
> 45 |         set_terminal_attr(&self.prev_ios).unwrap();
>    |         ^^^^^^^^^^^^^^^^^ not found in this scope
> 
> error[E0425]: cannot find function `get_terminal_attr` in this scope
>    --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:102:23
>     |
> 102 |         let mut ios = get_terminal_attr()?;
>     |                       ^^^^^^^^^^^^^^^^^ not found in this scope
> 
> error[E0425]: cannot find function `raw_terminal_attr` in this scope
>    --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:105:9
>     |
> 105 |         raw_terminal_attr(&mut ios);
>     |         ^^^^^^^^^^^^^^^^^ not found in this scope
> 
> error[E0425]: cannot find function `set_terminal_attr` in this scope
>    --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:107:9
>     |
> 107 |         set_terminal_attr(&ios)?;
>     |         ^^^^^^^^^^^^^^^^^ not found in this scope
> 
> error[E0425]: cannot find function `set_terminal_attr` in this scope
>    --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:119:9
>     |
> 119 |         set_terminal_attr(&self.prev_ios)?;
>     |         ^^^^^^^^^^^^^^^^^ not found in this scope
> 
> error[E0425]: cannot find function `get_terminal_attr` in this scope
>    --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:125:23
>     |
> 125 |         let mut ios = get_terminal_attr()?;
>     |                       ^^^^^^^^^^^^^^^^^ not found in this scope
> 
> error[E0425]: cannot find function `raw_terminal_attr` in this scope
>    --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:126:9
>     |
> 126 |         raw_terminal_attr(&mut ios);
>     |         ^^^^^^^^^^^^^^^^^ not found in this scope
> 
> error[E0425]: cannot find function `set_terminal_attr` in this scope
>    --> C:\Users\Tyler\.cargo\registry\src\github.com-1ecc6299db9ec823\termion-1.5.6\src\raw.rs:127:9
>     |
> 127 |         set_terminal_attr(&ios)?;
>     |         ^^^^^^^^^^^^^^^^^ not found in this scope
> 
>    Compiling addr2line v0.17.0
>    Compiling object v0.27.1
> Some errors have detailed explanations: E0425, E0432, E0433.
> For more information about an error, try `rustc --explain E0425`.
> error: could not compile `termion` due to 15 previous errors
> warning: build failed, waiting for other jobs to finish...
> error: failed to compile `cl-wordle v0.1.1`, intermediate artifacts can be found at `C:\Users\X\AppData\Local\Temp\cargo-install2SzPG7`
> ```

I think the sys crate is missing:
try following this instructions from microsoft: https://docs.microsoft.com/en-us/windows/dev-environment/rust/setup 
And maybe also try installing it with [chocolatey](https://chocolatey.org/)

I just installed the dependencies and got no errors, you probably didn't installed rust correctly.

**Comment by tylerjgarland** [comment]
@lastsoyce11 , I just installed rust though the rust website. I've never used it before. I'll uninstall and try through chocolatey.

**Comment by tylerjgarland** [comment]
@lastsoyce11 , still didn't work. Not sure what's going on, but too much effort at this point. lol

**Comment by conradludgate** [comment]
From [termion](https://github.com/redox-os/termion)

> Supports Redox, Mac OS X, BSD, and Linux (or, in general, ANSI terminals).

It might not support Windows, but I'm not 100% sure on that. I don't have access to a windows machine to test

**Comment by amuhs** [comment]
> still didn't work. Not sure what's going on, but too much effort at this point. lol

I get the same error as @tylerjgarland on Windows 10 (20H2). I would agree with @conradludgate, likely `termion` is the issue.

**Comment by conradludgate** [comment]
After some investigation, it seems that crossterm is a better crate, so I'm going to do a migration

**Comment by conradludgate** [comment]
I've published v0.1.8, please let me know if that compiles on windows

**Comment by amuhs** [comment]
Compiles! Thanks for the quick update. I would have loved to submit a PR, but I am only at the very beginning of learning rust and it would have taken a LONG time...

![windows-wordle](https://user-images.githubusercontent.com/13509797/152825825-da30e078-3dde-467a-8d7a-2f6eedf73905.png)

**Comment by conradludgate** [comment]
Awesome. I'll close this one for now, if you have any new issues, feel free to create a new one

**Comment by tylerjgarland** [comment]
@conradludgate , that fixed it! Thank you!
