### ISSUE TITLE
Off-by-one error?

### ISSUE THREAD

**Issue by afh** [conradludgate/wordle#25]
I noticed that the solution when playing this wordle seems to be off by one day compared to the solution of [New York Times' Wordle](https://www.nytimes.com/games/wordle/index.html) for the same day, i.e.
the solution for day 297 when playing this wordle is the solution for NYT's Wordle day 296.

A workaround that I've found is to add `+1` to `day` in [`src/word.rs`](https://github.com/conradludgate/wordle/blob/main/src/words.rs#L36), but this does not seem to the right path forward for a fix.

Happy to put up a PR if I could get a few pointers as to where the underlying issue may lie.

**Comment by conradludgate** [comment]
It may be that I copied the new word list incorrectly or that they have changed it again

**Comment by afh** [comment]
Thanks for addressing this so quickly, @conradludgate, can confirm that the words for days 296 and 297 are now as expected 🙏
