### ISSUE TITLE
a better Readme file

### ISSUE THREAD

**Issue by OrionRandD** [conradludgate/wordle#7]
Could you improve your Readme file?
What is wordle?
How to play it? - meaning, its rules and such...

**Comment by conradludgate** [comment]
Yeah, I should do. At the moment, I've assumed that most players come from the website and already know what to do

**Comment by OrionRandD** [comment]
> Yeah, I should do. At the moment, I've assumed that most players come from the website and already know what to do

Devs always forget that documentation is key in their codes and that not only programmers and technical people try to read and understand them...  :)
